[package]
name = "huffman"
version = "0.1.0"
edition = "2021"
description = "A Huffman compression utility."
license = "Unlicense"

[dependencies]
clap = {version = "4.5.21", features = ["derive"]}
testdir = "0.9.1"
bitvec = "1.0.1"
